package org.lenteja.test;

import java.util.Date;

import org.lenteja.mapper.Column;
import org.lenteja.mapper.Table;
import org.lenteja.mapper.autogen.impl.HsqldbSequence;

public class PersonTable extends Table<Person> {

    public final Column<Person, Long> idPerson = addPkColumn(Long.class, "id.idPerson");
    public final Column<Person, String> dni = addColumn(String.class, "id.dni");
    public final Column<Person, String> name = addColumn(String.class, "name");
    public final Column<Person, Integer> age = addColumn(Integer.class, "age");
    public final Column<Person, Date> birthDate = addColumn(Date.class, "birthDate");

    public PersonTable(String alias) {
        super("persons", alias);
        addAutoGenerated(new HsqldbSequence<>(idPerson, "seq_persons"));
    }

    public PersonTable() {
        this(null);
    }
}