
drop table tex if exists;
drop table exps if exists;

create table exps (
	 id_ens integer,
	 any_exp smallint,
	 num_exp integer generated by default as identity(start with 10),
	 name varchar(100) not null,
	 fecha_ini timestamp not null
);

alter table exps add constraint pk_id_exps primary key (id_ens,any_exp,num_exp);




create table tex (
	 id_tex integer primary key generated by default as identity(start with 100),
	 id_ens integer,
	 any_exp smallint,
	 num_exp integer,
	 fase_name varchar(100) not null
);

alter table tex add foreign key (id_ens,any_exp,num_exp) references exps(id_ens,any_exp,num_exp);


