
drop table pizzas if exists;
     
        
create table pizzas (
	 id_pizza integer,
	 name varchar(100) not null,
	 price numeric(5,2) not null,
	 kind varchar(20) not null
);



/******************************/



drop table dogs if exists;
drop table persons if exists;


drop sequence seq_persons if exists;
create sequence seq_persons start with 10;

create table persons (
	 id_person integer primary key not null,
	 dni varchar(20) not null,
	 name varchar(30) not null,
	 age smallint not null,
	 birth_date timestamp not null
);


create table dogs (
	 id_dog smallint generated by default as identity(start with 100),
	 name varchar(20) not null,
	 is_alive boolean not null, 
	 sex varchar(10) not null,
	 id_jefe integer not null
);

alter table dogs add foreign key (id_jefe) references persons(id_person);




