


drop table pizza_ingredients if exists;
drop table pizzas if exists;
drop table ingredients if exists;

create table pizzas (
	 id_pizza integer primary key generated by default as identity(start with 100),
	 name varchar(100) not null
);

create table ingredients (
	 id_ingredient smallint primary key generated by default as identity(start with 100),
	 name varchar(100) not null
);

create table pizza_ingredients (
	 id_pizza integer,
	 id_ingredient smallint
);

alter table pizza_ingredients add constraint pk_pizza_ingredients primary key (id_pizza,id_ingredient);
alter table pizza_ingredients add foreign key (id_pizza) references pizzas(id_pizza);
alter table pizza_ingredients add foreign key (id_ingredient) references ingredients(id_ingredient);



