/*

	 tickets --* ticket_user *-- users
   	   ||                          ||
   	   |+------* ticket_msg *------+|
       +-------* state_trans *------+
*/


drop table state_trans if exists;
drop table ticket_msg if exists;
drop table ticket_user if exists;
drop table tickets if exists;
drop table users if exists;


create table tickets (
	 id_tick integer primary key generated by default as identity(start with 10),
	 title varchar(100) not null,
	 created timestamp not null
);
create table users (
	 id_user integer primary key generated by default as identity(start with 100),
	 email varchar(100) not null
);

create table ticket_user (
	id_tick integer,
	id_user integer
);
alter table ticket_user add constraint pk_id_ticket_user primary key (id_tick,id_user);
alter table ticket_user add foreign key (id_tick) references tickets(id_tick);
alter table ticket_user add foreign key (id_user) references users(id_user);

create table ticket_msg (
	id_tick integer,
	id_user integer,
	message varchar(200) not null,
	moment timestamp not null
);
alter table ticket_msg add constraint pk_id_ticket_msg primary key (id_tick,id_user);
alter table ticket_msg add foreign key (id_tick) references tickets(id_tick);
alter table ticket_msg add foreign key (id_user) references users(id_user);

create table state_trans (
	id_tick integer,
	id_user integer,
	state varchar(20) not null,
	moment timestamp not null
);
alter table state_trans add constraint pk_id_state_trans primary key (id_tick,id_user);
alter table state_trans add foreign key (id_tick) references tickets(id_tick);
alter table state_trans add foreign key (id_user) references users(id_user);









