
drop table tex if exists;
drop table exps if exists;

create table exps (
	 id_ens integer,
	 any_exp smallint,
	 num_exp integer generated by default as identity(start with 10),
	 name varchar(100) not null,
	 fecha_ini varchar(15) not null,
	 sex varchar(100) not null,
	 alive boolean not null
);
